title: STEFANIA POZZI
description:
url: "https://sunnyStefi.github.io"
baseurl: ""

author:
  name: Stefania

theme: minima
minima:
  skin: dark

permalink: /:year/:month/:day/:title/
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag
